server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springfolio?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.community.domain
  configuration:
    map-underscore-to-camel-case: true

app:
  rss:
    feeds:
      - https://www.yonhapnewstv.co.kr/browse/feed/           # 연합뉴스TV 속보
      - https://rss.donga.com/total.xml                       # 동아일보 종합
      - https://www.hani.co.kr/rss/lead/                      # 한겨레 주요뉴스
      - https://feeds.bbci.co.uk/news/rss.xml                  # BBC News
      - https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml # 뉴욕타임스
      - https://www.reuters.com/rssFeed/worldNews